server:
  port: 5671

##spring setting
spring:
  main:
    banner-mode: off
  profiles:
    active: dev
  application:
    name: boot_rabbitmq

  ## redis
  redis:
    database: 0
    host: 49.235.64.160
    port: 6379
    password: zgq123456
    timeout: 60000
    ## 是否启用redis 工具类配置
    utils:
      enable=true:


  ## rabbitmq
  cloud:
    stream:
      #假如有多个rabbitmq 需要使用，可以设置多个binder
      binders:
        # binder名称：test
        test:
          # binder类型：rabbit/kafka
          type: rabbit
          #　连接属性
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.218
                port: 5672
                username: admin
                password: 123456
        #test2:
        #  type: rabbit
        #  environment:
        #    spring:
        #      rabbitmq:
        #        host: 192.168.2.51
        #        port: 5672
        #        username: test
        #        password: test

##log setting
logging:
  level:
    com:
      boot:
        rabbitmq: debug
        redis: debug
    ##rabbitmq 启动日志
    org:
      springframework:
        amqp:
          rabbit:
            connection: debug
#logging.level.org.springframework.amqp=debug
