spring:
  cloud:
    stream:
      default-binder: test
      ##
      bindings:
        ## 开启分区消费的主题队列
        mq-partition-input:
          destination: mq-partition
          group: mq-demo
          content-type: application/json
          binder: test
          consumer:
            concurrency: 1
            max-attempts: 1
            # 开启消费者分区
            partitioned: true
        mq-partition-output:
          destination: mq-partition
          group: mq-demo
          content-type: application/json
          binder: test
          producer:
            concurrency: 1
            max-attempts: 1
            # 指定消费分区数量
            partitionCount: 2
            # 分区规则表达式（此处为payload中的header 值）
            partitionKeyExpression: payload.mid
            par
